name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          repositories_affiliations: ""
          token: ${{ secrets.METRICS_TOKEN }}
          
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          filename: metrics.plugin.calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0          
          repositories_affiliations: ""

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          repositories_affiliations: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: >-
            css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, arduino
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

      - name: Mildly interesting facts
        uses: lowlighter/metrics@latest
        with:
          config_timezone: America/Sao_Paulo
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          config_timezone: America/Sao_Paulo

      - name: Most used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, arduino
          plugin_languages_limit: 6
          config_timezone: America/Sao_Paulo
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

      - name: Most used (with details)
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, arduino
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
          config_timezone: America/Sao_Paulo
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

      - name: Recently used
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 6
          config_timezone: America/Sao_Paulo
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365

      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          repositories_affiliations: ""
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            css, tex, less, dockerfile, makefile, qmake, lex, cmake, gnuplot, arduino
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 6
          plugin_languages_analysis_timeout: 60
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 365
